app/styleme/website/views.py
from flask import jsonify, request, render_template
from flask import Blueprint, render_template, url_for, request, session, redirect, Flask, jsonify, flash, make_response
from google.cloud import storage, vision
from werkzeug.utils import secure_filename
import io
import json
import datetime
import hashlib
import random
import string
import os
import google.generativeai as palm
from google.cloud import storage
from google.cloud import datastore
import requests
import re
import random
from website.keywords import clothing_keywords, color_keywords
#from flask_cors import CORS



config_file = os.getenv('CONFIG_FILE')

print(f"The value of CONFIG_FILE is: {config_file}")

with open(config_file) as f:
    config = json.load(f)



views = Blueprint('views', __name__)
#CORS(views)

@views.route('/health', methods=['GET'])
def get_service_health():

    response = {
      "status": "healthy",  
      "app_name": "styleme",   
      "status_code":200
                }
        
    return jsonify(response), 200

storage_client = storage.Client()



@views.route('/', methods=['POST', 'GET'])
def styleme():
    if request.method == 'POST':
        try:
            request_data = request.get_json()
            conversation_list = request_data.get('conversation')
            user_persona = request_data.get('persona')

            # Store the conversation in the datastore
            store_conversation_in_datastore({"conversation": conversation_list})

            # Prepare data for demographic analysis
            chat = convert_conversation_list_to_plain_text(conversation_list)
            data = {"chat": chat}
            demographic_endpoint = '/service/ai/demographic_json'
            demographic_api_url = f"{config['BASE_URL']}{demographic_endpoint}"

            # Make a request to the demographic analysis API
            demographic_response = requests.post(demographic_api_url, json=data)

            if demographic_response.status_code == 200:
                response_data = demographic_response.json()
                response_string = response_data.get('response')
                 
                if response_string is not None:
                    response_dict = json.loads(response_string)

                    # Filter out "not provided" values
                    filtered_response_dict = {key: value for key, value in response_dict.items() if value != "not provided"}
                    filtered_response_dict["user_persona"] = user_persona
                    print(f'filtered_response_dict:{filtered_response_dict}')
                    # Request product matching based on demographic analysis
                    product_matching_endpoint = '/product/match'
                    product_matching_api_url = f"{config['BASE_URL']}{product_matching_endpoint}"

                    response = requests.post(product_matching_api_url, json=filtered_response_dict)

                    if response.status_code == 200:
                        return jsonify(response.json()), 200
                    else:
                        return jsonify({'error': f"Request to /product/match failed with status code {response.status_code}"}), 500
                else:
                    return jsonify({'error': "The 'response' key was not found in the JSON response."}), 500
            else:
                return jsonify({'error': f"Request to the demographic API failed with status code {demographic_response.status_code}"}), 500
        except Exception as e:
            return jsonify({'error': str(e)}, 500)
    else:
        # Handle the GET request by fetching and rendering products
        products = fetch_products_styleme()
        return render_template('styleme.html', products=products)



'''@views.route('/', methods=['POST', 'GET'])
def styleme():
    if request.method == 'POST':
        try:
            request_data = request.get_json()
            print(request_data)
            conversation_list = request_data.get('conversation')
            chat = convert_conversation_list_to_plain_text(conversation_list)
            conversation = parse_conversation(chat)
            chat_conversation = {"conversation": conversation}
            
            response_message = store_conversation_in_datastore(chat_conversation)

            data = {"chat": chat}
            
            print(data)
            endpoint = '/service/ai/demographic_json'
            api_url = f"{BASE_URL}{endpoint}"
           
            response = requests.post(api_url, json=data)
            print(response)
            print(response.text)


            if response.status_code == 200:
                try:
                    # Parse the JSON response
                    response_data = response.json()
                    response_string = response_data.get('response')
                    print(response_string)

                    if response_string is not None:
                        # Decode the inner JSON
                        response_dict = json.loads(response_string)

                        # Create a new dictionary with non-"not provided" values
                        filtered_response_dict = {key: value for key, value in response_dict.items() if value != "not provided"}

                        # Print the filtered response
                        print(filtered_response_dict)

                        # You can return or use the filtered_response_dict as needed
                    else:
                        print("The 'response' key was not found in the JSON response.")
                except json.JSONDecodeError as e:
                    print("Failed to parse the JSON response from the API:", str(e))
            else:
                # Handle errors if the request was not successful
                print("Request failed with status code:", response.status_code)
                print("Error message:", response.text)



        except Exception as e:
            print("Error:", str(e))
        endpoint = '/service/product/description'
        api_url = f"{BASE_URL}{endpoint}" # Replace with the actual URL

        # Create a dictionary with the 'query' key and the response data
        request_data = {"query": " ".join(filtered_response_dict.values())}

        # Send a POST request to the API
        response = requests.post(api_url, json=request_data)
        print(response.json())

        if response.status_code == 200:
            # Process the response from the '/service/product/description' endpoint
            
            return jsonify(response.json()), 200
            
        
        else:
            # Handle errors if the request was not successful
            print("Request to /service/product/description failed with status code:", response.status_code)
            print("Error message:", response.text)

        # If any error occurs or no products are found, return an empty JSON
       

    else:
        
        products = fetch_products_styleme()
        return render_template('styleme.html', products=products)'''
    


def fetch_products_styleme():
    endpoint = '/service/product/all_products'
    api_url = f"{config['BASE_URL']}{endpoint}"
    response = requests.get(api_url)  # Replace with your actual API URL
    products = response.json()
    return products[:2]

@views.route('/stylemeqna', methods=['POST'])
def styleme_qna():
    # Get the magazine_id from the session
    conversation_list = []
    data = request.get_json()

    # Access the selected persona and question
    user_persona = data.get('persona')
    question = data.get('question')
    print(data)
    chat = convert_conversation_list_to_plain_text(conversation_list)
    
    
    answer = ask_question_from_fashion(question,user_persona)
        
    conversation_list.append({'User': question, 'Fashion Advisor': answer})
    #print(conversation_list)
    # Return the answer as a JSON response
    return jsonify({'answer': answer})


def convert_conversation_list_to_plain_text(conversation_list):
  """
  Converts a conversation list to plain text.

  Args:
    conversation_list: A list of conversation objects.

  Returns:
    A string of plain text representing the conversation.
  """

  plain_text = ""
  for conversation in conversation_list:
    plain_text += f"User: {conversation['User']}\n"
    plain_text += f"Fashion Advisor: {conversation['Fashion Advisor']}\n"
    print(plain_text)
  return plain_text



def ask_question_from_fashion(data,user_persona):
    try:
        
        #endpoint = '/service/ai/fashionqna'
        endpoint = '/service/ai/stylemebot'
        api_url = f"{config['api_url_stylemebot']}{endpoint}"
        #api_url_stylemebot = 'https://dev-gen-ai-service-styleme-chat-kcvokjzgdq-ew.a.run.app/service/ai/stylemebot'
        payload = {
            'chat': data,
            'user_persona': user_persona
            
        }

        response = requests.post(api_url, json=payload)
        response.raise_for_status()  # Raise an exception for HTTP errors
        return response.json().get('answer', 'Sorry, I couldn\'t find an answer.')
    except requests.exceptions.RequestException as e:
        # Handle the exception and return an error response
        return 'An error occurred while communicating with the chatbot.'
# Initialize an empty list to store the conversation
#conversation_list = []
def parse_conversation(text):
    lines = text.strip().split('\n')
    conversation = []
    sender = None
    current_message = []

    for line in lines:
        line = line.strip()
        if line.startswith('User:'):
            if sender and current_message:
                conversation.append({"sender": sender, "message": ' '.join(current_message)})

app/styleme/website/templates/navbar.html
<!-- Use Bootstrap container for better content alignment -->
  
<nav class="navbar bg-body-tertiary fixed-top" style="padding: 0%;">
   
   
     
    
    <div class="d-flex ">
      

      
  <!-- Project Selector Dropdown -->
  

      
      <!-- Logo placed beside the toggler -->
      <a class="navbar-nav" href="#">
        <img src="../static/stylemepage/COG-Logo-2022-8.svg" alt="Logo" width="150" height="60" class="d-inline-block align-text-top">
      </a>


      
      <!-- Project Selector Dropdown -->
      
      
    
     
      <!-- Rest of your navigation content follows... -->
    </div>
    <div class="innovation-gallery">
        <a href="https://dev-dashboard-kcvokjzgdq-ew.a.run.app/">Home</a>
      </div>
      
   
    
    
    
  </nav>

app/styleme/website/templates/styleme.html
<!DOCTYPE html>
<html>

<head>
  <title>Styleme</title>
  <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename ='stylemepage/styles.css') }}">

  <!-- Add Bootstrap CSS link -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.12.1/css/all.css" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css">
</head>
<meta name="viewport" content="width=device-width, initial-scale=1">

<body>
  {% include "navbar.html" %}
<br>
<br>
<br><br>
    <style>
        .btn-black-grey {
            background-color: #333; /* Black background color */
            color: #ccc; /* Grey text color */
            border: 1px solid #ccc; /* Grey border */
        }
        .btn-black-grey:hover {
            background-color: #444; /* Darker black on hover */
            color: #fff; /* White text on hover */
            border: 1px solid #444; /* Darker grey border on hover */
        }
    </style>

    <!-- Main Content -->
    <div class="container-fluid">
        <div class="persona-container" style=" margin-top: -30px;">
        <div class="persona-title">Persona:</div>
        <div class="persona-content">
        <div class="customize-input">
            <input type="text" id="customInput" name="custom_input" placeholder="Custom Persona Input">
        </div>
      <div class="select-dropdown">
        <select id="personaSelect" name="user_persona">
            <option value="boys">Boys</option>
            <option value="girls">Girls</option>
            <option value="teenage_men">Teenage Men</option>
            <option value="teenage_girls">Teenage Girls</option>
            <option value="young_adult_men">Young Adult Men</option>
            <option value="young_adult_women">Young Adult Women</option>
            <option value="men">Men</option>
            <option value="women">Women</option>
              <!-- Add more persona options as needed -->
          </select>
        </div>
    </div>
      </div>
        <div class="row">
            <div class="col-md-6">
                <div class="chat-container" style="margin-top: 12px;">
                    <div class="chat-box" id="chat-box">
                        <!-- Bot messages will be displayed here -->
                        <div class="message bot-message">Hello! How can I assist you today?</div>
                    </div>
                    <div class="input-container">
                        <input id="user-input" class="form-control" type="text" placeholder="Type your message...">
                        <button id="send-button" class="btn btn-outline-secondary">Send</button>
                    </div>
                    
                    
                </div>
            </div>
            
            
          
        
            <div class="col-md-6">
                <div class="container-fluid product-container" >
                        {% for product in products %}
                        <div class="product">
                            <a href="{{ url_for('views.styleme', product_id=product.product_ID) }}">
                                <img src="{{ product.image_URL }}" alt="{{ product.product_name }}">
                                <h2>{{ product.product_name }}</h2>
                                <p>${{ product.price }}</p>
                            </a>   
                        </div>
                        {% endfor %}
                    </div>
            </div>
        </div>
    </div>
     <!-- <div class="container1">
      <button id="info-button" class="circular-button">i</button>
      <div id="info-panel" class="info-panel">
          <div class="close-button" id="close-button">X</div>
          <h4>GenAI WebApp</h4>
          <p>Team Members:</p>
          <div class="team-members">
            {% for member in team_members_info %}
                <div class="team-member-card">
                    <div class="team-member-name">{{ member.name }}</div>
                    <div class="team-member-role">{{ member.role }}</div>
                </div>
            {% endfor %}
          </div>
      </div>
    </div>  -->
   
    

    <!-- Scripts -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm"
        crossorigin="anonymous"></script>
    <script src="../static/stylemepage/scripts.js"></script>
    

</body>

</html>